linters:
  disable-all: false
  enable:
    - dogsled
    - errname
    - errorlint
  disable:
    - structcheck # disabled by default in Go 1.18 - just to hide warning

linters-settings:
  govet:
    disable:
      - composites # for mongo syntax