version: '3'

services:
  customers-api:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: umalmyha/customers
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - MONGO_URL=${MONGO_URL}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_MAX_RETRIES=${REDIS_MAX_RETRIES}
      - REDIS_POOL_SIZE=${REDIS_POOL_SIZE}
      - AUTH_JWT_ISSUER=${AUTH_JWT_ISSUER}
      - AUTH_JWT_TIME_TO_LIVE=${AUTH_JWT_TIME_TO_LIVE}
      - AUTH_JWT_PRIVATE_KEY_FILE=${AUTH_JWT_PRIVATE_KEY_FILE}
      - AUTH_JWT_PUBLIC_KEY_FILE=${AUTH_JWT_PUBLIC_KEY_FILE}
      - AUTH_REFRESH_TOKEN_MAX_COUNT=${AUTH_REFRESH_TOKEN_MAX_COUNT}
      - AUTH_REFRESH_TOKEN_TIME_TO_LIVE=${AUTH_REFRESH_TOKEN_TIME_TO_LIVE}
    restart: always
    depends_on:
      - pg-customers
      - flyway
      - mongo-customers
      - redis-customers
    ports:
      - "3000:3000"
      - "3010:3010"
    volumes:
      - customer-images:/app/images

  pg-customers:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgcustomers:/var/lib/postgresql/data

  redis-customers:
    image: "redis:latest"
    command:
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - customer-redis:/data

  mongo-customers:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongocustomers:/data/db

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://pg-customers:5432/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - pg-customers

volumes:
  pgcustomers:
  mongocustomers:
  customer-images:
  customer-redis: