// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/umalmyha/customers/internal/model"
)

// CustomerRepository is an autogenerated mock type for the CustomerRepository type
type CustomerRepository struct {
	mock.Mock
}

type CustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomerRepository) EXPECT() *CustomerRepository_Expecter {
	return &CustomerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *CustomerRepository) Create(_a0 context.Context, _a1 *model.Customer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Customer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CustomerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 *model.Customer
func (_e *CustomerRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *CustomerRepository_Create_Call {
	return &CustomerRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *CustomerRepository_Create_Call) Run(run func(_a0 context.Context, _a1 *model.Customer)) *CustomerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Customer))
	})
	return _c
}

func (_c *CustomerRepository_Create_Call) Return(_a0 error) *CustomerRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

// DeleteByID provides a mock function with given fields: _a0, _a1
func (_m *CustomerRepository) DeleteByID(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type CustomerRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 string
func (_e *CustomerRepository_Expecter) DeleteByID(_a0 interface{}, _a1 interface{}) *CustomerRepository_DeleteByID_Call {
	return &CustomerRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", _a0, _a1)}
}

func (_c *CustomerRepository_DeleteByID_Call) Run(run func(_a0 context.Context, _a1 string)) *CustomerRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CustomerRepository_DeleteByID_Call) Return(_a0 error) *CustomerRepository_DeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

// FindAll provides a mock function with given fields: _a0
func (_m *CustomerRepository) FindAll(_a0 context.Context) ([]*model.Customer, error) {
	ret := _m.Called(_a0)

	var r0 []*model.Customer
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Customer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomerRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type CustomerRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//  - _a0 context.Context
func (_e *CustomerRepository_Expecter) FindAll(_a0 interface{}) *CustomerRepository_FindAll_Call {
	return &CustomerRepository_FindAll_Call{Call: _e.mock.On("FindAll", _a0)}
}

func (_c *CustomerRepository_FindAll_Call) Run(run func(_a0 context.Context)) *CustomerRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CustomerRepository_FindAll_Call) Return(_a0 []*model.Customer, _a1 error) *CustomerRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FindByID provides a mock function with given fields: _a0, _a1
func (_m *CustomerRepository) FindByID(_a0 context.Context, _a1 string) (*model.Customer, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.Customer
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Customer); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomerRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type CustomerRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 string
func (_e *CustomerRepository_Expecter) FindByID(_a0 interface{}, _a1 interface{}) *CustomerRepository_FindByID_Call {
	return &CustomerRepository_FindByID_Call{Call: _e.mock.On("FindByID", _a0, _a1)}
}

func (_c *CustomerRepository_FindByID_Call) Run(run func(_a0 context.Context, _a1 string)) *CustomerRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CustomerRepository_FindByID_Call) Return(_a0 *model.Customer, _a1 error) *CustomerRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *CustomerRepository) Update(_a0 context.Context, _a1 *model.Customer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Customer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CustomerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 *model.Customer
func (_e *CustomerRepository_Expecter) Update(_a0 interface{}, _a1 interface{}) *CustomerRepository_Update_Call {
	return &CustomerRepository_Update_Call{Call: _e.mock.On("Update", _a0, _a1)}
}

func (_c *CustomerRepository_Update_Call) Run(run func(_a0 context.Context, _a1 *model.Customer)) *CustomerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Customer))
	})
	return _c
}

func (_c *CustomerRepository_Update_Call) Return(_a0 error) *CustomerRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewCustomerRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCustomerRepository creates a new instance of CustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCustomerRepository(t mockConstructorTestingTNewCustomerRepository) *CustomerRepository {
	mock := &CustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
