// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/umalmyha/customers/internal/model"
)

// RefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type RefreshTokenRepository struct {
	mock.Mock
}

type RefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenRepository) EXPECT() *RefreshTokenRepository_Expecter {
	return &RefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *RefreshTokenRepository) Create(_a0 context.Context, _a1 *model.RefreshToken) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.RefreshToken) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 *model.RefreshToken
func (_e *RefreshTokenRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *RefreshTokenRepository_Create_Call {
	return &RefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *RefreshTokenRepository_Create_Call) Run(run func(_a0 context.Context, _a1 *model.RefreshToken)) *RefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.RefreshToken))
	})
	return _c
}

func (_c *RefreshTokenRepository_Create_Call) Return(_a0 error) *RefreshTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

// DeleteByID provides a mock function with given fields: _a0, _a1
func (_m *RefreshTokenRepository) DeleteByID(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type RefreshTokenRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 string
func (_e *RefreshTokenRepository_Expecter) DeleteByID(_a0 interface{}, _a1 interface{}) *RefreshTokenRepository_DeleteByID_Call {
	return &RefreshTokenRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", _a0, _a1)}
}

func (_c *RefreshTokenRepository_DeleteByID_Call) Run(run func(_a0 context.Context, _a1 string)) *RefreshTokenRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshTokenRepository_DeleteByID_Call) Return(_a0 error) *RefreshTokenRepository_DeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

// DeleteByUserID provides a mock function with given fields: _a0, _a1
func (_m *RefreshTokenRepository) DeleteByUserID(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type RefreshTokenRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 string
func (_e *RefreshTokenRepository_Expecter) DeleteByUserID(_a0 interface{}, _a1 interface{}) *RefreshTokenRepository_DeleteByUserID_Call {
	return &RefreshTokenRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", _a0, _a1)}
}

func (_c *RefreshTokenRepository_DeleteByUserID_Call) Run(run func(_a0 context.Context, _a1 string)) *RefreshTokenRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshTokenRepository_DeleteByUserID_Call) Return(_a0 error) *RefreshTokenRepository_DeleteByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

// FindByID provides a mock function with given fields: _a0, _a1
func (_m *RefreshTokenRepository) FindByID(_a0 context.Context, _a1 string) (*model.RefreshToken, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.RefreshToken
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.RefreshToken); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RefreshToken)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type RefreshTokenRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 string
func (_e *RefreshTokenRepository_Expecter) FindByID(_a0 interface{}, _a1 interface{}) *RefreshTokenRepository_FindByID_Call {
	return &RefreshTokenRepository_FindByID_Call{Call: _e.mock.On("FindByID", _a0, _a1)}
}

func (_c *RefreshTokenRepository_FindByID_Call) Run(run func(_a0 context.Context, _a1 string)) *RefreshTokenRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshTokenRepository_FindByID_Call) Return(_a0 *model.RefreshToken, _a1 error) *RefreshTokenRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// FindTokensByUserID provides a mock function with given fields: _a0, _a1
func (_m *RefreshTokenRepository) FindTokensByUserID(_a0 context.Context, _a1 string) ([]*model.RefreshToken, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []*model.RefreshToken
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.RefreshToken); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RefreshToken)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenRepository_FindTokensByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTokensByUserID'
type RefreshTokenRepository_FindTokensByUserID_Call struct {
	*mock.Call
}

// FindTokensByUserID is a helper method to define mock.On call
//  - _a0 context.Context
//  - _a1 string
func (_e *RefreshTokenRepository_Expecter) FindTokensByUserID(_a0 interface{}, _a1 interface{}) *RefreshTokenRepository_FindTokensByUserID_Call {
	return &RefreshTokenRepository_FindTokensByUserID_Call{Call: _e.mock.On("FindTokensByUserID", _a0, _a1)}
}

func (_c *RefreshTokenRepository_FindTokensByUserID_Call) Run(run func(_a0 context.Context, _a1 string)) *RefreshTokenRepository_FindTokensByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshTokenRepository_FindTokensByUserID_Call) Return(_a0 []*model.RefreshToken, _a1 error) *RefreshTokenRepository_FindTokensByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewRefreshTokenRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRefreshTokenRepository creates a new instance of RefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRefreshTokenRepository(t mockConstructorTestingTNewRefreshTokenRepository) *RefreshTokenRepository {
	mock := &RefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
