CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE CUSTOMERS(
    ID UUID DEFAULT uuid_generate_v4(),
    FIRST_NAME VARCHAR(200) NOT NULL,
    LAST_NAME VARCHAR(200) NOT NULL,
    MIDDLE_NAME VARCHAR(200),
    EMAIL VARCHAR(250) NOT NULL,
    IMPORTANCE INT DEFAULT 1,
    INACTIVE BOOLEAN DEFAULT FALSE,
    PRIMARY KEY(ID)
);